[book]
language = "en"
multilingual = false
src = "src"
title = "Programista.de"
description = "Programista na dzikim zachodzie"
authors = ["Tomasz Sapletta"]
[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/programista-de/book"
git-repository-icon = "fa-github"
[output.html.search]
limit-results = 15
